name = "TensorBranching"
uuid = "86172e9d-0750-4338-909c-b7a43d7b620d"
authors = ["Xuanzhao Gao <gaoxuanzhao@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
